In [1]:
import xgboost as xgb
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
features = pd.read_csv('CreacionDeFeatures/trainingSet2.csv')
testing = pd.read_csv('CreacionDeFeatures/testingSet2.csv')

labels = pd.read_csv('CreacionDeFeatures/Data/labels_training_set.csv')

In [3]:
features = features.set_index('person')

features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,sony,bcm,vam,vao,coam,coao,cam,cao,lam,lao
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
labels = labels.set_index('person')

labels.head()

          label
person
0566e9c1      0
6ec7ee77      0
abe7a2fb      0
34728364      0
87ed62de      0

In [5]:
data = features.merge(labels, left_index=True, right_index=True)

data.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,bcm,vam,vao,coam,coao,cam,cao,lam,lao,label
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [6]:
features, labels = data.iloc[:,:-1],data.iloc[:,-1]

In [7]:
features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,sony,bcm,vam,vao,coam,coao,cam,cao,lam,lao
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
labels.head()

#Estan en el mismo orden

person
0008ed71    0
000c79fe    0
001802e4    0
0019e639    0
001b0bf9    0
Name: label, dtype: int64

In [9]:
features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.2, random_state=123)

In [10]:
params = {
        'min_child_weight': [1, 5, 10, 15, 20, 25],
        'gamma': [0.5, 1, 1.5, 2, 5, 10],
        'reg_alpha': [0, 2, 4, 6, 8, 10],
        'subsample': [0.2, 0.4, 0.6, 0.8, 1.0],
        'colsample_bytree': [0.2 ,0.4 ,0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5, 6, 7, 8],
        'n_estimators': [50, 100, 150, 200, 250, 300, 350, 400],
        'learning_rate': [0.01, 0.015, 0.02, 0.025, 0.03]
        }

In [11]:
from sklearn.model_selection import StratifiedKFold

folds = 3
param_comb = 750

skf = StratifiedKFold(n_splits=folds, shuffle = True, random_state = 1001)

In [12]:
xgb_class = xgb.XGBClassifier(objective='binary:logistic',
                    silent=True, nthread=1, scale_pos_weight = 19.8)

In [13]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

random_search = RandomizedSearchCV(xgb_class, param_distributions=params, n_iter=param_comb, scoring='roc_auc', n_jobs=4, cv=skf.split(features,labels), verbose=3, random_state=1001 )

In [14]:
random_search.get_params

<bound method BaseEstimator.get_params of RandomizedSearchCV(cv=<generator object _BaseKFold.split at 0x0000028900DD6258>,
          error_score='raise-deprecating',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=1, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=19.8, seed=None,
       silent=True, subsample=1),
          fit_params=None, iid='warn', n_iter=750, n_jobs=4,
          param_distributions={'min_child_weight': [1, 5, 10, 15, 20, 25], 'gamma': [0.5, 1, 1.5, 2, 5, 10], 'reg_alpha': [0, 2, 4, 6, 8, 10], 'subsample': [0.2, 0.4, 0.6, 0.8, 1.0], 'colsample_bytree': [0.2, 0.4, 0.6, 0.8, 1.0], 'max_depth': [3, 4, 5, 6, 7, 8], 'n_estimators': [50, 100, 150, 200, 250, 300, 350, 400], 'learning_rate': [0.01, 0.015, 0.02, 0.025, 0.03]},
          pre_dispatch='2*n_jobs', random_state=1001, refit=True,
          return_train_score='warn', scoring='roc_auc', verbose=3)>

In [15]:
result = random_search.fit(features, labels)

Fitting 3 folds for each of 750 candidates, totalling 2250 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   27.9s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:  1.7min
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:  3.7min
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed:  6.7min
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed: 10.8min
[Parallel(n_jobs=4)]: Done 1144 tasks      | elapsed: 15.6min
[Parallel(n_jobs=4)]: Done 1560 tasks      | elapsed: 21.7min
[Parallel(n_jobs=4)]: Done 2040 tasks      | elapsed: 28.1min
[Parallel(n_jobs=4)]: Done 2250 out of 2250 | elapsed: 30.6min finished

In [16]:
result.best_params_

{'subsample': 0.8,
 'reg_alpha': 4,
 'n_estimators': 200,
 'min_child_weight': 20,
 'max_depth': 3,
 'learning_rate': 0.025,
 'gamma': 5,
 'colsample_bytree': 0.8}

In [17]:
params = {
        'subsample': [0.6, 0.8],
        'min_child_weight': [20, 40, 45, 50],
        'gamma': [0.5, 2.5, 5],
        'max_depth': [3, 4],
        'reg_alpha': [3, 4],
        'n_estimators': [200 ,300],
        'learning_rate': [0.02, 0.025],
        'colsample_bytree': [0.8]
        }

In [18]:
grid_search = GridSearchCV(xgb_class, param_grid=params, scoring='roc_auc', n_jobs=4, cv=skf.split(features,labels), verbose=3)

In [19]:
result2 = grid_search.fit(features, labels)

Fitting 3 folds for each of 384 candidates, totalling 1152 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   18.2s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:  1.5min
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:  3.7min
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed:  6.8min
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed: 10.8min
[Parallel(n_jobs=4)]: Done 1144 tasks      | elapsed: 15.7min
[Parallel(n_jobs=4)]: Done 1152 out of 1152 | elapsed: 15.8min finished

In [20]:
result2.best_params_

{'colsample_bytree': 0.8,
 'gamma': 5,
 'learning_rate': 0.025,
 'max_depth': 3,
 'min_child_weight': 40,
 'n_estimators': 200,
 'reg_alpha': 4,
 'subsample': 0.8}