In [36]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [37]:
randomForest = RandomForestClassifier(n_estimators=100, max_depth=5, min_samples_leaf=50, class_weight='balanced')

In [38]:
features = pd.read_csv('CreacionDeFeatures/trainingSet.csv')
testing = pd.read_csv('CreacionDeFeatures/testingSet.csv')
testing = testing.set_index('person')

labels = pd.read_csv('CreacionDeFeatures/Data/labels_training_set.csv')

In [39]:
features = features.set_index('person')

features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,EntraronConTablet,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos,CantidadDiasDiferentesDeVisita,CantidadDeModelosVistos,EsDeBrazil,DiasDeActividadDeUsuario,DiasDesdeUltimoSearchHit
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,1000.0,1000.0,3,1,3,1.0,1.0,1000.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,3.0,1,1,1,1.0,1.0,3.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,5.0,1.0,1.0,2,1,2,1.0,1.0,1000.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,0.0,29.0,10.0,10.0,14,14,26,1.0,115.0,10.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,1000.0,1000.0,2,1,1,0.0,1.0,1000.0

In [40]:
labels = labels.set_index('person')

labels.head()

          label
person
0566e9c1      0
6ec7ee77      0
abe7a2fb      0
34728364      0
87ed62de      0

In [41]:
data = features.merge(labels, left_index=True, right_index=True)

data.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos,CantidadDiasDiferentesDeVisita,CantidadDeModelosVistos,EsDeBrazil,DiasDeActividadDeUsuario,DiasDesdeUltimoSearchHit,label
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,1000.0,1000.0,3,1,3,1.0,1.0,1000.0,0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,3.0,3.0,1,1,1,1.0,1.0,3.0,0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,5.0,1.0,1.0,2,1,2,1.0,1.0,1000.0,0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,29.0,10.0,10.0,14,14,26,1.0,115.0,10.0,0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,1000.0,1000.0,2,1,1,0.0,1.0,1000.0,0

In [42]:
features, labels = data.iloc[:,:-1],data.iloc[:,-1]

In [43]:
features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,EntraronConTablet,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos,CantidadDiasDiferentesDeVisita,CantidadDeModelosVistos,EsDeBrazil,DiasDeActividadDeUsuario,DiasDesdeUltimoSearchHit
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,1000.0,1000.0,3,1,3,1.0,1.0,1000.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,3.0,1,1,1,1.0,1.0,3.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,5.0,1.0,1.0,2,1,2,1.0,1.0,1000.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,0.0,29.0,10.0,10.0,14,14,26,1.0,115.0,10.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,1000.0,1000.0,2,1,1,0.0,1.0,1000.0

In [44]:
labels.head()

#Estan en el mismo orden

person
0008ed71    0
000c79fe    0
001802e4    0
0019e639    0
001b0bf9    0
Name: label, dtype: int64

In [45]:
features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=153)

In [46]:
randomForest.fit(features_train, labels_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=5, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=50,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [47]:
randomForest.score(features_test,labels_test)

0.7960515021459228

In [48]:
preds = randomForest.predict(testing)

In [49]:
randomForestFinal = RandomForestClassifier(n_estimators=100, max_depth=5, min_samples_leaf=50, class_weight='balanced')

In [50]:
randomForestFinal.fit(features, labels)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=5, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=50,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [51]:
preds = randomForestFinal.predict(testing)

In [52]:
preds.sum()

4809

In [53]:
preds

array([0, 1, 0, ..., 1, 1, 0], dtype=int64)

In [54]:
sample = pd.read_csv('CreacionDeFeatures/Data/trocafone_kaggle_submit_sample_all_0.csv')

In [55]:
sample = sample.set_index('person')

sample.head()

          label
person
4886f805      0
0297fc1e      0
2d681dd8      0
cccea85e      0
4c8a8b93      0

In [56]:
sample = sample.sort_index()

sample.head()

          label
person
00091926      0
00091a7a      0
000ba417      0
000e4d9e      0
000e619d      0

In [57]:
sample['label'] = preds

sample.head()

          label
person
00091926      0
00091a7a      1
000ba417      0
000e4d9e      0
000e619d      0

In [58]:
#sample.to_csv('predicciones.csv')

In [61]:
feature_importances = pd.DataFrame(randomForestFinal.feature_importances_,
                                   index = features.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)

feature_importances

                                importance
DiasDesdeUltimoCheckout           0.343889
CantidadCheckouts                 0.207682
DiasDesdePrimerEvento             0.079420
DiasDesdeUltimoEvento             0.074153
CantidadEventos                   0.048532
DiasDeActividadDeUsuario          0.036009
EntraronConComputadora            0.025630
DiasDesdeUltimoSearchHit          0.022765
CantidadDiasDiferentesDeVisita    0.022563
CantidadDeModelosVistos           0.021758
DiasDesdeUltimaConversion         0.016731
DiasDesdeUltimoAdHit              0.016086
PromedioVentasPorMes              0.014150
CantidadDeColoresVistos           0.011193
CantidadSearchEngineHits          0.010942
DiasDesdeUltimaBusqueda           0.010329
EntraronMasDeUnaVez               0.009546
CantidadCompras                   0.009212
CantidadAdHits                    0.005606
EntraronConSmartphone             0.004601
VentasHaceUnMes                   0.003891
VentasHaceDosMeses                0.003429
VentasMes3                        0.001021
EsDeBrazil                        0.000355
VentasMes4                        0.000272
EntraronConTablet                 0.000224
CantidadLeads                     0.000010
VentasMes2                        0.000000
LeadsHaceUnMes                    0.000000
LeadsHaceDosMeses                 0.000000
VentasMes1                        0.000000