In [46]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [47]:
randomForest = RandomForestClassifier(n_estimators=100, max_depth=5, min_samples_leaf=50, class_weight='balanced')

In [48]:
features = pd.read_csv('CreacionDeFeatures/trainingSet.csv')
testing = pd.read_csv('CreacionDeFeatures/testingSet.csv')
testing = testing.set_index('person')

labels = pd.read_csv('CreacionDeFeatures/Data/labels_training_set.csv')

In [49]:
features = features.set_index('person')

features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,CantidadSearchEngineHits,EntraronMasDeUnaVez,DiasDesdeUltimoCheckout,EntraronConComputadora,EntraronConSmartphone,EntraronConTablet,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,1.0,15.0,1.0,0.0,0.0,0.0,1000.0,1000.0,3
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,3.0,0.0,1.0,0.0,1.0,3.0,3.0,1
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,5.0,1.0,1.0,2
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,13.0,1.0,10.0,1.0,0.0,0.0,29.0,10.0,10.0,14
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,1000.0,1000.0,2

In [50]:
labels = labels.set_index('person')

labels.head()

          label
person
0566e9c1      0
6ec7ee77      0
abe7a2fb      0
34728364      0
87ed62de      0

In [51]:
data = features.merge(labels, left_index=True, right_index=True)

data.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,EntraronMasDeUnaVez,DiasDesdeUltimoCheckout,EntraronConComputadora,EntraronConSmartphone,EntraronConTablet,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos,label
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,1.0,15.0,1.0,0.0,0.0,0.0,1000.0,1000.0,3,0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,3.0,0.0,1.0,0.0,1.0,3.0,3.0,1,0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,5.0,1.0,1.0,2,0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,1.0,10.0,1.0,0.0,0.0,29.0,10.0,10.0,14,0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,10.0,0.0,0.0,0.0,0.0,1000.0,1000.0,2,0

In [52]:
features, labels = data.iloc[:,:-1],data.iloc[:,-1]

In [53]:
features.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,...,CantidadSearchEngineHits,EntraronMasDeUnaVez,DiasDesdeUltimoCheckout,EntraronConComputadora,EntraronConSmartphone,EntraronConTablet,CantidadAdHits,DiasDesdeUltimoAdHit,DiasDesdeUltimaBusqueda,CantidadDeColoresVistos
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,1.0,15.0,1.0,0.0,0.0,0.0,1000.0,1000.0,3
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,3.0,0.0,1.0,0.0,1.0,3.0,3.0,1
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,5.0,1.0,1.0,2
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,...,13.0,1.0,10.0,1.0,0.0,0.0,29.0,10.0,10.0,14
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,1000.0,1000.0,2

In [54]:
labels.head()

#Estan en el mismo orden

person
0008ed71    0
000c79fe    0
001802e4    0
0019e639    0
001b0bf9    0
Name: label, dtype: int64

In [55]:
features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=153)

In [56]:
randomForest.fit(features_train, labels_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=5, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=50,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [57]:
randomForest.score(features_test,labels_test)

0.8078969957081545

In [58]:
preds = randomForest.predict(testing)

In [59]:
randomForestFinal = RandomForestClassifier(n_estimators=100, max_depth=5, min_samples_leaf=50, class_weight='balanced')

In [60]:
randomForestFinal.fit(features, labels)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=5, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=50,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [61]:
preds = randomForestFinal.predict(testing)

In [62]:
preds.sum()

4509

In [63]:
preds

array([0, 1, 0, ..., 1, 1, 0], dtype=int64)

In [64]:
sample = pd.read_csv('CreacionDeFeatures/Data/trocafone_kaggle_submit_sample_all_0.csv')

In [65]:
sample = sample.set_index('person')

sample.head()

          label
person
4886f805      0
0297fc1e      0
2d681dd8      0
cccea85e      0
4c8a8b93      0

In [66]:
sample = sample.sort_index()

sample.head()

          label
person
00091926      0
00091a7a      0
000ba417      0
000e4d9e      0
000e619d      0

In [68]:
sample['label'] = preds

sample.head()

          label
person
00091926      0
00091a7a      1
000ba417      0
000e4d9e      0
000e619d      0

In [70]:
sample.to_csv('predicciones.csv')