In [7]:
import pandas as pd
import numpy as np
import datetime

In [8]:
logsTrocafone = pd.read_csv('Data/events_up_to_01062018.csv', low_memory = False)

trainingSet = pd.read_csv('trainingSet.csv')
trainingSet = trainingSet.set_index('person')

testingSet = pd.read_csv('testingSet.csv')
testingSet = testingSet.set_index('person')

trainingSet.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,VentasMes3,VentasMes4,PromedioVentasPorMes,DiasDesdeUltimoEvento,DiasDesdePrimerEvento,DiasDesdeUltimoCheckout,DiasDesdeUltimaConversion,CantidadSearchEngineHits
person,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,15.0,15.0,15.0,10000.0,0.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,3.0,10000.0,1.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,10000.0,0.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,0.0,0.0,0.4,10.0,124.0,10.0,10.0,13.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.2,10.0,10.0,10.0,10.0,0.0

In [9]:
returning = logsTrocafone.loc[logsTrocafone['new_vs_returning'] == 'Returning', :]

returning.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
2136629,2018-05-10 22:34:50,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Paid,Returning,Nova Esperanca,Parana,Brazil,Smartphone,320x570,Android 5.0.2,Chrome Mobile 66.0
2136630,2018-05-15 02:39:45,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Paid,Returning,Nova Esperanca,Parana,Brazil,Smartphone,320x570,Android 5.0.2,Chrome Mobile 66.0
2136631,2018-05-18 01:15:26,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Paid,Returning,Unknown,Unknown,Brazil,Computer,1280x1024,Ubuntu,Firefox 57
2136632,2018-05-18 19:03:37,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Paid,Returning,Nova Esperanca,Parana,Brazil,Tablet,800x1280,Android 7,Chrome 66.0
2136633,2018-05-18 19:35:12,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Organic,Returning,Nova Esperanca,Parana,Brazil,Tablet,800x1280,Android 7,Chrome 66.0

In [10]:
returning['ColumnaDe1'] = 1

returning.head()

C:\Users\marti\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,ColumnaDe1
2136629,2018-05-10 22:34:50,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Paid,Returning,Nova Esperanca,Parana,Brazil,Smartphone,320x570,Android 5.0.2,Chrome Mobile 66.0,1
2136630,2018-05-15 02:39:45,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Paid,Returning,Nova Esperanca,Parana,Brazil,Smartphone,320x570,Android 5.0.2,Chrome Mobile 66.0,1
2136631,2018-05-18 01:15:26,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Paid,Returning,Unknown,Unknown,Brazil,Computer,1280x1024,Ubuntu,Firefox 57,1
2136632,2018-05-18 19:03:37,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Paid,Returning,Nova Esperanca,Parana,Brazil,Tablet,800x1280,Android 7,Chrome 66.0,1
2136633,2018-05-18 19:35:12,visited site,4640420b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Organic,Returning,Nova Esperanca,Parana,Brazil,Tablet,800x1280,Android 7,Chrome 66.0,1

In [11]:
personasQueVolvieron = returning.groupby('person').agg({'ColumnaDe1':'max'})

personasQueVolvieron.head()

          ColumnaDe1
person
0008ed71           1
00091926           1
000ba417           1
000e4d9e           1
000e619d           1

In [12]:
nuevoTrainingSet = trainingSet.merge(personasQueVolvieron, how='left', left_index=True, right_index=True)

nuevoTrainingSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19414 entries, 0008ed71 to fff78145
Data columns (total 19 columns):
CantidadEventos              19414 non-null int64
CantidadCompras              19414 non-null float64
CantidadLeads                19414 non-null float64
VentasHaceUnMes              19414 non-null float64
LeadsHaceUnMes               19414 non-null float64
VentasHaceDosMeses           19414 non-null float64
LeadsHaceDosMeses            19414 non-null float64
CantidadCheckouts            19414 non-null float64
VentasMes1                   19414 non-null float64
VentasMes2                   19414 non-null float64
VentasMes3                   19414 non-null float64
VentasMes4                   19414 non-null float64
PromedioVentasPorMes         19414 non-null float64
DiasDesdeUltimoEvento        19414 non-null float64
DiasDesdePrimerEvento        19414 non-null float64
DiasDesdeUltimoCheckout      19414 non-null float64
DiasDesdeUltimaConversion    19414 non-null float64
CantidadSearchEngineHits     19414 non-null float64
ColumnaDe1                   11730 non-null float64
dtypes: float64(18), int64(1)
memory usage: 3.6+ MB

In [13]:
nuevoTestingSet = testingSet.merge(personasQueVolvieron, how='left', left_index=True, right_index=True)

nuevoTestingSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19415 entries, 00091926 to fffd1246
Data columns (total 19 columns):
CantidadEventos              19415 non-null int64
CantidadCompras              19415 non-null float64
CantidadLeads                19415 non-null float64
VentasHaceUnMes              19415 non-null float64
LeadsHaceUnMes               19415 non-null float64
VentasHaceDosMeses           19415 non-null float64
LeadsHaceDosMeses            19415 non-null float64
CantidadCheckouts            19415 non-null float64
VentasMes1                   19415 non-null float64
VentasMes2                   19415 non-null float64
VentasMes3                   19415 non-null float64
VentasMes4                   19415 non-null float64
PromedioVentasPorMes         19415 non-null float64
DiasDesdeUltimoEvento        19415 non-null float64
DiasDesdePrimerEvento        19415 non-null float64
DiasDesdeUltimoChechout      19415 non-null float64
DiasDesdeUltimaConversion    19415 non-null float64
CantidadSearchEngineHits     19415 non-null float64
ColumnaDe1                   11784 non-null float64
dtypes: float64(18), int64(1)
memory usage: 3.6+ MB

In [14]:
nuevoTestingSet = nuevoTestingSet.fillna(0)

nuevoTestingSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19415 entries, 00091926 to fffd1246
Data columns (total 19 columns):
CantidadEventos              19415 non-null int64
CantidadCompras              19415 non-null float64
CantidadLeads                19415 non-null float64
VentasHaceUnMes              19415 non-null float64
LeadsHaceUnMes               19415 non-null float64
VentasHaceDosMeses           19415 non-null float64
LeadsHaceDosMeses            19415 non-null float64
CantidadCheckouts            19415 non-null float64
VentasMes1                   19415 non-null float64
VentasMes2                   19415 non-null float64
VentasMes3                   19415 non-null float64
VentasMes4                   19415 non-null float64
PromedioVentasPorMes         19415 non-null float64
DiasDesdeUltimoEvento        19415 non-null float64
DiasDesdePrimerEvento        19415 non-null float64
DiasDesdeUltimoChechout      19415 non-null float64
DiasDesdeUltimaConversion    19415 non-null float64
CantidadSearchEngineHits     19415 non-null float64
ColumnaDe1                   19415 non-null float64
dtypes: float64(18), int64(1)
memory usage: 3.6+ MB

In [15]:
nuevoTrainingSet = nuevoTrainingSet.fillna(0)

nuevoTrainingSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19414 entries, 0008ed71 to fff78145
Data columns (total 19 columns):
CantidadEventos              19414 non-null int64
CantidadCompras              19414 non-null float64
CantidadLeads                19414 non-null float64
VentasHaceUnMes              19414 non-null float64
LeadsHaceUnMes               19414 non-null float64
VentasHaceDosMeses           19414 non-null float64
LeadsHaceDosMeses            19414 non-null float64
CantidadCheckouts            19414 non-null float64
VentasMes1                   19414 non-null float64
VentasMes2                   19414 non-null float64
VentasMes3                   19414 non-null float64
VentasMes4                   19414 non-null float64
PromedioVentasPorMes         19414 non-null float64
DiasDesdeUltimoEvento        19414 non-null float64
DiasDesdePrimerEvento        19414 non-null float64
DiasDesdeUltimoCheckout      19414 non-null float64
DiasDesdeUltimaConversion    19414 non-null float64
CantidadSearchEngineHits     19414 non-null float64
ColumnaDe1                   19414 non-null float64
dtypes: float64(18), int64(1)
memory usage: 3.6+ MB

In [16]:
nuevoTrainingSet = nuevoTrainingSet.rename(columns={"ColumnaDe1": "EntraronMasDeUnaVez"})

nuevoTestingSet = nuevoTestingSet.rename(columns={"ColumnaDe1": "EntraronMasDeUnaVez"})

In [17]:
nuevoTrainingSet.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,VentasMes3,VentasMes4,PromedioVentasPorMes,DiasDesdeUltimoEvento,DiasDesdePrimerEvento,DiasDesdeUltimoCheckout,DiasDesdeUltimaConversion,CantidadSearchEngineHits,EntraronMasDeUnaVez
person,,,,,,,,,,,,,,,,,,,
0008ed71,6,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,15.0,15.0,15.0,10000.0,0.0,1.0
000c79fe,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,3.0,10000.0,1.0,0.0
001802e4,19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,10000.0,0.0,0.0
0019e639,471,2.0,0.0,1.0,0.0,1.0,0.0,15.0,0.0,1.0,0.0,0.0,0.4,10.0,124.0,10.0,10.0,13.0,1.0
001b0bf9,7,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.2,10.0,10.0,10.0,10.0,0.0,0.0

In [18]:
nuevoTestingSet.head()

,CantidadEventos,CantidadCompras,CantidadLeads,VentasHaceUnMes,LeadsHaceUnMes,VentasHaceDosMeses,LeadsHaceDosMeses,CantidadCheckouts,VentasMes1,VentasMes2,VentasMes3,VentasMes4,PromedioVentasPorMes,DiasDesdeUltimoEvento,DiasDesdePrimerEvento,DiasDesdeUltimoChechout,DiasDesdeUltimaConversion,CantidadSearchEngineHits,EntraronMasDeUnaVez
person,,,,,,,,,,,,,,,,,,,
00091926,448,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,29.0,6.0,10000.0,0.0,1.0
00091a7a,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,67.0,10000.0,10000.0,0.0,0.0
000ba417,206,1.0,0.0,1.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,0.2,6.0,15.0,6.0,6.0,1.0,1.0
000e4d9e,411,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,16.0,16.0,10000.0,5.0,1.0
000e619d,68,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14.0,17.0,15.0,10000.0,3.0,1.0

In [19]:
#nuevoTrainingSet.to_csv('trainingSet.csv')
#Este comando reemplaza el training set existente con la feature agregada

In [20]:
#nuevoTestingSet.to_csv('testingSet.csv')
#Este comando reemplaza el testing set existente con la feature agregada